name: Validate data

on:
  pull_request:
    paths:
      - "sources/**"
      - "schema.json"
  push:
    branches: [main]
    paths:
      - "sources/**"
      - "schema.json"

jobs:
  call:
    uses: migiwa-ya/dataset-workflows/.github/workflows/validate-reusable.yml@main
    with:
      schema: schema.json
